### ISSUE TITLE
棒！

### ISSUE THREAD

**Issue by Yves0** [dgeibi/switch-systemd-unit#1]
刚添加 SSR 的 systemd 单元就看见你这个辅助
我觉得更理想的是使用 dmenu 切换配置，像 [Networkmanager-dmenu](https://github.com/firecat53/networkmanager-dmenu)
前两天看到一个 [electron-ssr](https://github.com/erguotou520/electron-ssr) 客户端，不过现在还 bug 多多的样子

**Comment by dgeibi** [comment]
😁 多谢鼓励！

切换一般unit需要root的权限，弄成cli，sudo输密码简单呀～

**Comment by Yves0** [comment]
刚刚发现一个不错的 [ssr-helper](https://github.com/duyamin/ssr-helper)，主要是可以添加订阅贼爽，一键添加所有配置 💯
